# Generated by Django 3.2.4 on 2021-06-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PassengerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Passenger',
        ),
    ]
