# Generated by Django 3.2.4 on 2021-06-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassengerApp', '0002_rename_student_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
