# Generated by Django 3.2.4 on 2021-06-16 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstRest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.AddField(
            model_name='department',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstRest.employee'),
        ),
    ]
